server:
  port: 22000
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://user:123456@peer1:8761/eureka/,http://user:123456@peer2:8762/eureka/,http://user:123456@peer3:8763/eureka/

spring:
  application:
    name: provider